//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dividends.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dividend
    {
        public int Id { get; set; }
        public string Symbol { get; set; }
        public string Name { get; set; }
        public string Sector { get; set; }
        public Nullable<double> MarketCap { get; set; }
        public Nullable<double> Beta { get; set; }
        public Nullable<double> DividendYield { get; set; }
        public Nullable<double> PERatio { get; set; }
        public Nullable<double> Score { get; set; }
        public Nullable<double> DividendGrowthStreak { get; set; }
        public Nullable<double> UninterruptedDividendStreak { get; set; }
        public string PaymentFrequency { get; set; }
    }
}
